<?php

namespace AppBundle\Repository;

/**
 * responsable_caninRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class responsable_caninRepository extends \Doctrine\ORM\EntityRepository
{
}
