<?php

namespace AppBundle\Repository;

/**
 * spaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class spaRepository extends \Doctrine\ORM\EntityRepository
{
}
